[package]
name = "ockam_entity"
version = "0.7.0-dev"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_entity"
readme = "README.md"
categories = ["cryptography", "authentication"]
keywords = ["ockam", "crypto", "encryption", "authentication"]
description = """Ockam is a library for building devices that communicate securely, privately
and trustfully with cloud services and other devices.
"""

[features]
default = ["std", "noise_xx"]
noise_xx = ["ockam_key_exchange_xx"]
std = []

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.18.0-dev"            }
ockam_node = {path = "../ockam_node", version = "0.16.0-dev"           }
ockam_vault = {path = "../ockam_vault", version = "0.12.0-dev"         }
ockam_channel = {path = "../ockam_channel", version = "0.13.0-dev"          }
ockam_key_exchange_xx = { path = "../ockam_key_exchange_xx", version = "0.10.0-dev"           , optional = true}
async-trait = "0.1.42"
bls12_381_plus = "0.5"
cfg-if = "1.0.0"
group = "0.10.0"
heapless = "0.7"
serde = { version = "1.0", default-features = false, features = ["derive"] }
signature_core = { path = "../signature_core", version = "0.10.0-dev"}
signature_bls = { path = "../signature_bls", version = "0.8.0-dev"}
signature_bbs_plus = { path = "../signature_bbs_plus", version = "0.10.0-dev"}
sha2 = "0.9"
serde-big-array = "0.3"
serde_bare = "0.4"
rand = "0.8"
tracing = "0.1"

[dev-dependencies]
ockam_transport_tcp = { path = "../ockam_transport_tcp"}
rand_xorshift = "0"
